### ISSUE TITLE
Compilation errors hidden if previous file already exists

### ISSUE THREAD

**Issue by amoffat** [cyberdelia/django-pipeline#421]
The situation I'm running into is a bad sass file fails to compile, but because an old compile succeeded, the new compile thinks everything is fine and hides the error.  The relevant line is https://github.com/cyberdelia/django-pipeline/blob/master/pipeline/compilers/__init__.py#L43

I'm not sure why the compiled file existing would silence the exception from being raised.  What's the reasoning behind this?

**Comment by cyberdelia** [comment]
That's a very old behaviour, this was introduced a long time ago (the project wasn't even named django-pipeline at the time), so that you don't fail in production when a compiled file already exists.

This seems very wrong today, with how compilation works today, I've fixed it in f3fa679f30af5d705d91022a3f09762ca23d7334.

Thanks a lot for spotting it :bowtie:
